# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Runs a set of commands using the runners shell
    - name: Docker login
      env: 
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }} 
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
         docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    
    # Building docker image
    - name: Building docker image
      run: docker build -t notes-frontend:latest .
    
    # Docker Push
    - name: Docker push
      run: |
        echo 'Tagging image'
        docker tag notes-frontend:latest ${{ secrets.DOCKER_HUB_USER }}/notes-frontend:latest
        
        echo 'Pushing image to repository'
        docker push ${{ secrets.DOCKER_HUB_USER }}/notes-app-service:latest
